---
title: "roni-shen-lab06"
author: "Roni Shen"
date: "10/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Manipulating and Visualizing Data Frames

```{r eval = FALSE}

mkdir lab06
cd lab06
mkdir data
mkdir code
mkdir output 
mkdir images 
touch README.md
cd datacurl -O https://raw.githubusercontent.com/ucb-stat133/stat133-fall-2018/master/data/nba2018-players.csv
ls 
wc nba2018-players.csv
head nba2018-players.csv
tail -n 5 nba2018-players.csv

```


## Exporting some data tables 

```{r}

library(readr)
library(dplyr)
library(ggplot2)

# Use read_csv() from the package "readr" to import the data nba2018-players.csv in R. Do this by specifying a relative path.
dat  <- read_csv("../data/nba2018-players.csv")

# Use the imported tibble to create a data frame warriors by selecting rows—e.g. filter()—of Golden State Warriors, arranging rows by salary in increasing order.
warriors <- arrange(filter(dat, team == "GSW"), salary)

# Use the function write.csv() to export (or save) the data frame warriors to a data file warriors.csv in the folder/ directory. You will need to use a relative path to specify the file argument. Also, see how to use the argument row.names to avoid including a first column of numbers.
write.csv(warriors, file = "../data/warriors.csv", row.names = FALSE)

# Create another data frame lakers by selecting rows of Los Angeles Lakers, this time arranging rows by experience (decreasingly).
lakers <- arrange(filter(dat, team == "LAL"), desc(experience))

# Now use the function write_csv() to export (or save) the data frame lakers to a data file lakers.csv in the folder/ directory. You will also need to use a relative path to specify the file argument.
write_csv(lakers, "../data/lakers.csv")

```


## Exporting some R output

```{r}

# divert output to the specified file
sink(file = '../output/summary-height-weight.txt')
summary(dat[ ,c('height', 'weight')])
sink()

# Export the output of str() on the data frame with all the players. sink() the output, using a relative path, to a text file data-structure.txt, in the output/ folder.
sink(file = "../output/data-structure.txt")
str(dat)
sink()

# Export the summary() of the entire data frame warriors to a text file summary-warriors.txt, in the output/ folder (also use a relative path).
sink(file = "../output/summary-warriors.txt")
summary(warriors)
sink()

# Export another summary() of the entire data frame lakers to a text file summary-lakers.txt, in the output/ folder (using a relative path).
sink(file = "../output/summary-lakers.txt")
summary(lakers)
sink()

```


## Exporting some “base” graphs

```{r}

# saving a scatterplot in png format
png(filename = "../images/scatterplot-height-weight.png")
plot(dat$height, dat$weight, pch = 20, 
     xlab = 'Height', ylab = 'Height')
dev.off()

# Open the help documentation of png() and related graphic devices.
?png

# Use png() to save a scatterplot of height and weight with plot(). Save the graph in the images/ folder.
png(filename = "../images/scatterplot-height-weight.png")
plot(dat$height, dat$weight, xlab = "height", ylab = "weight", main = "Height and Weight of NBA Players 2018")
dev.off()

# Save another version of the scatterplot between height and weight, but now try to get an image with higher resolution. Save the plot in images/.
png(filename = "../images/scatterplot-height-weight2.png", res = 100)
plot(dat$height, dat$weight, xlab = "Height", ylab = "Weight", main = "Height and Weight of NBA Players 2018")
dev.off()


# Save a histogram in JPEG format of age with dimensions (width x height) 600 x 400 pixels. Save the plot in images/.
jpeg("../images/histogram-age.jpeg", width = 600, height = 400)
hist(dat$age, xlab = "Age", main = "Age of NBA Players 2018")
dev.off()

# Use pdf() to save the previous histogram of age in PDF format, with dimensions (width x height) 7 x 5 inches.
pdf("../images/histogram-age.pdf", width = 7, height = 5)
hist(dat$age, xlab = "Age", main = "Age of NBA Players 2018")
dev.off()

# Use ggplot() to make a scatterplot of points and salary, and store it in a ggplot object named gg_pts_salary. Then use ggsave() to save the plot with dimensions (width x height) 7 x 5 inches; in the images/ folder as points_salary.pdf
gg_pts_salary <- ggplot(data = dat, aes(x = points, y = salary)) + geom_point() + ggtitle("Points and Salary of NBA Players 2018")
ggsave("../images/points_salary.pdf", gg_pts_salary, width = 7, height = 5)

# Use ggplot() to create a scatterplot of height and weight, faceting by position. Store this in a ggplot object gg_ht_wt_positions Then use ggsave() to save the plot with dimensions (width x height) 6 x 4 inches; in the images/ folder as height_weight_by_position.pdf
gg_ht_wt_positions <-  ggplot(dat, aes(x = height, y = weight)) + geom_point() + facet_wrap(~position) + ggtitle("Height and Wegiht of NBA Players 2018 by Position")
ggsave("../images/height_weight_by_position.pdf", gg_ht_wt_positions, width = 6, height = 4)

```


## More "dplyr"

```{r}

# display the player names of Lakers 'LAL'.
dat %>% select(player)

# display the name and salary of GSW point guards ‘PG’.
warriors %>% 
  filter(position == "PG") %>% 
  select(player, salary)

# dislay the name, age, and team, of players with more than 10 years of experience, making 10 million dollars or less.
dat %>% 
  filter(experience > 10, salary > 10000000) %>% 
  select(player, age, team)

# select the name, team, height, and weight, of rookie players, 20 years old, displaying only the first five occurrences (i.e. rows).
dat %>% 
  filter(experience == 0, age == 20) %>% 
  select(player, team, height, weight) %>% 
  head(5)

# create a data frame gsw_mpg of GSW players, that contains variables for player name, experience, and min_per_game (minutes per game), sorted by min_per_game (in descending order).
gsw_mpg <- warriors %>% 
  mutate(min_per_game = minutes/games) %>%
  select(player, experience, min_per_game) %>%
  arrange(desc(min_per_game))

# display the average triple points by team, in ascending order, of the bottom-5 teams (worst 3pointer teams).
dat %>% 
  group_by(team) %>% 
  select(team, points3) %>% 
  summarise(
    averge_3_pointers = mean(points3)
  ) %>% 
  head(5)
  
# obtain the mean and standard deviation of age, for Power Forwards, with 5 and 10 years (including) of experience.
dat %>%
  filter(position == "PF", experience >= 5 & experience <= 10) %>% 
  select(age) %>% 
  summarise(
    mean_age = mean(age),
    sd_age = sd(age)
  )
  


```
