---
title: "lab09-roni-shen"
author: "Roni Shen"
date: "10/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```


## Part 1) Practice writing simple tests

```{r}

# assuming that your working directory is "lab09/"
library(testthat)
test_file("tests.R")

```


## Part 2) Basics of String Manipulation

```{r}

# number of characters
states <- rownames(USArrests)
num_chars <- nchar(states)

# paste chararcter vectors with seperator (default = black space)
paste('Pumpkin', 'Pie')
paste('a', 'b', 'c', 'd', 'e')
paste('a', 'b', 'c', 'd', 'e', sep = '-')

# paste() is vectorized
paste('a', 1:5, sep = '.')

# paste0() -vs- paste(..., sep = "")
paste0('Pumpkin', 'Pie')

# paste0() is also vectorized
paste0('a', 1:5)

# your turn 
paste(states[1:5], num_chars[1:5], sep = " = ")
paste(states[1:5], collapse = "")

# number of permutations that can be formed by using all the given letters in ALABAMA
factorial(7) / factorial(3)

# substrings
# extract first 3 characters
substr('Berkeley', 1, 3)

# Use substr() to shorten the state names using the first 3-letters:
substr(states, 1, 3)

# Use substr() to shorten the state names using the last 3-letters:
substr(states, num_chars - 2, num_chars)

# How would you shorten the state names using the first letter and the last 3-letters
paste0(substr(states, 1, 1), substr(states, num_chars - 2, num_chars))

# challenge
states_list = list()
for (i in 4:10) {
  if (i %% 2 == 0) {
    states_list = c(states_list, list(paste(toupper(states[num_chars == i]), collapse = ", ")))
  } else {
    states_list = c(states_list, list(paste(tolower(states[num_chars == i]), collapse = ", ")))
  }
  names(states_list)[i-3] =  paste0(i, "-chars")
}

# Converting from Fahrenheit Degrees
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  switch(tolower(to),
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')

# Names of files
# vector of file names
file_names1 = paste("file", 1:10, ".csv", sep = "")
paste(paste0("file", 1:10), "csv", sep = ".")
paste0("file", 1:10, ".csv", sep = "")

# rename vector of file names
file_names2 = paste0("dataset", substr(file_names1, 5, length(file_names1)))

# Using function cat()
# name of output file
outfile <- "output.txt" 

# your turn
cat("---", "\ntitle: 'lab09-roni-shen'", "\nauthor: 'Roni Shen'", "\ndate: '10/24/2018'", "\noutput: html_document", "\n---\n\n", file = outfile)
# writing to 'outfile.txt'
cat("This is the first line", file = outfile, append = TRUE)
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)

# Valid Color Names
#' @title is color
#' @description test if it is a valid color in R
#' @param x a color (string)
#' @return TRUE or FALSE
is_color <- function(x) {
  if (x %in% colors()) {
    TRUE
  } else {
    FALSE 
  }
}

# test it:
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE

# Plot with a valid color
#' @title is color
#' @description test if it is a valid color in R
#' @param col a color (string)
#' @return TRUE or FALSE
colplot <- function(col) {
  if (is_color(col)) {
    plot(rnorm(1:100), rnorm(1:100), main = paste0("Testing color ", col), col = col)
  } else {
    stop("invalid color ", col) 
  }
}

# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')

```